### ISSUE TITLE
Redmine 3.XX Compatibility

### ISSUE THREAD

**Issue by jmdziba** [peelman/my_projects#11]
Love this plugin.  Are you planning on making it compatible with Redmine 3.x?

Regards,
Josh

**Comment by braini75** [comment]
Hi Josh,
it a very small fix. You can try my fork until peelman updates the master branch.
Test: https://github.com/braini75/my_projects.git

**Comment by peelman** [comment]
@braini75 I'm happy to pull in your changes if you send me a PR :)

**Comment by braini75** [comment]
I guess this can be closed!
